[package]
name = "rust-niko-niko"
version = "0.1.0"
authors = ["Jean-David Génevaux <jd.genevaux@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.2.23"
enum-map = "0.6.4"